### ISSUE TITLE
Cleanup JavaScript issues identified by CodeClimate

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#145]
[![Code Climate](https://codeclimate.com/github/zen-audio-player/zen-audio-player.github.io/badges/gpa.svg)](https://codeclimate.com/github/zen-audio-player/zen-audio-player.github.io)

[![Issue Count](https://codeclimate.com/github/zen-audio-player/zen-audio-player.github.io/badges/issue_count.svg)](https://codeclimate.com/github/zen-audio-player/zen-audio-player.github.io)

You can see the list of issues by clicking the banner directly above. The issues we should be concerned about are mostly around similar/duplicated code, console statements and TODOs are secondary concerns.

**Comment by shakeelmohamed** [comment]
Once we cleanup these ~[20 issues](https://codeclimate.com/github/zen-audio-player/zen-audio-player.github.io/issues), we can add code climate to the status checks required for each PR

**Comment by eirism** [comment]
I have started to refactor some of the offending code. I can fix the other issues if this looks good.

**Comment by shakeelmohamed** [comment]
Rock on @eirism!

**Comment by eirism** [comment]
What should we do about the console statements? Just get rid of them?

**Comment by shakeelmohamed** [comment]
You can integrate in the following settings to the `.codeclimate.yml` file - we already have the `eslint` property

```yaml
engines:
  # ... CONFIG CONTENT ...
  eslint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      no-console:
        enabled: false
# ... CONFIG CONTENT ...
```
